Repository googlestadia/PorQue4K, pull requests merged in 2020-06, with the labels that each got.

#30 Amend incorrect references to HLSL `sample` modifiers
  docs/CHECKERBOARD.md
Labels: documentation

#33 Fix Linux X11 build
  README.md
  src/app/AppCore.h
  src/app/AppRender.cpp
  src/app/AppUtil.cpp
  src/app/main.cpp
Labels: bug

#36 Enable float16/int8 support to device
  src/app/main.cpp
  src/vkex/Device.cpp
  src/vkex/Device.h
Labels: enhancement

#37 Validation fix: Match counts for color blend attachment states to color attachments
  src/app/main.cpp
Labels: bug
